#!/bin/bash

# Get the directory where the script is located
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Check if the correct number of arguments are provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <INPUT_STRING>"
    exit 1
fi

# Assign arguments to variables

input_string="$1"

# Run the Python script with the provided arguments
"$script_dir/agrep.py" "$input_string"
